### ISSUE TITLE
packagist auto update

### ISSUE THREAD

**Issue by pfefferle** [willnorris/wordpress-license#4]
@willnorris can you add the auto-updated for packagist?

https://packagist.org/packages/willnorris/wordpress-license

**Comment by willnorris** [comment]
I'd be happy to, but I don't actually understand what you're asking me to do.  I've never used packagist.

**Comment by willnorris** [comment]
never mind, I think I figured it out.  I configured the service, though I'm not sure how to test it.  There's a "test service" button on GitHub, but I'm not sure what I'm looking for to verify that it worked.

**Comment by pfefferle** [comment]
the "auto-update" notification on packagist is gone, so I think you have done it correctly, thanks! :)

**Comment by pfefferle** [comment]
@willnorris your first packagist package: https://packagist.org/packages/willnorris/wordpress-license :smile:

**Comment by pfefferle** [comment]
I will also add a doku how to install/update the plugin via composer

**Comment by willnorris** [comment]
hah.  Thanks for helping get it setup. :)
